### ISSUE TITLE
Deployment pipeline for ECS with AWS CodePipeline

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-microservices-deploy-options#104]
Create a deployment pipeline for tasks deployed in ECS using AWS CodePipeline

**Comment by MitchyBAwesome** [comment]
I've got a whole stack of reusable content form the cats and dogs workshop you can use here. Feel free to assign this one to me if you'd like.

**Comment by anshrma** [comment]
@MitchyBAwesome - I havent started on it yet and likely maybe able to start only by next week. So if you have cycles available, you may take this up. Thanks

**Comment by arun-gupta** [comment]
This would be addressed by:
https://github.com/aws-samples/aws-microservices-deploy-options/pull/219
https://github.com/aws-samples/aws-microservices-deploy-options/pull/222
https://github.com/aws-samples/aws-microservices-deploy-options/pull/229

@MitchyBAwesome will test out for EC2-mode tasks. File bugs if there are any issues.
