### ISSUE TITLE
Incorrect command for getting the list of VPCs

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-microservices-deploy-options#132]
Command to get the list of VPCs is incorrect:

```
$ aws ec2 describe-vpcs \
>   --query 'Vpcs[?IsDefault=`true`].VpcId'

Bad value for --query Vpcs[?IsDefault=`true`].VpcId: Bad jmespath expression: Unknown token '=':
Vpcs[?IsDefault=`true`].VpcId
               ^
```

It should be:

```
$ aws ec2 describe-vpcs \
>   --query 'Vpcs[?IsDefault==`true`].VpcId'
```

**Comment by Nakulgr** [comment]
I am facing similar issue --> Bad jmespath expression: Unknown token '-':

export VPCENDPOINTSERVICENAME=$(aws managedblockchain get-network --region $REGION --network-id $NETWORKID --query 'Network.com.amazonaws.us-east-1.managedblockchain.n-7K4UXKIATBD4HGVE7BTFQDBHC4' --output text)

Bad value for --query Network.com.amazonaws.us-east-1.managedblockchain.n-7K4UXKIATBD4HGVE7BTFQDBHC4: Bad jmespath expression: Unknown token '-':
Network.com.amazonaws.us-east-1.managedblockchain.n-7K4UXKIATBD4HGVE7BTFQDBHC4

Can you please suggest a way forward ?
