### ISSUE TITLE
ECS EC2 Mode awsvpc vs bridge mode

### ISSUE THREAD

**Issue by tiffanyfj** [aws-samples/aws-microservices-deploy-options#137]
Look into adding capabilities for using load balancer and bridge mode.

**Comment by arun-gupta** [comment]
Default mode for EC2 is `bridge` and the default mode for Fargate is `awsvpc`. @tiffanyfj will add a slide explaining the difference between the two.

**Comment by arun-gupta** [comment]
@tiffanyfj provided the slides [slides-for-arun(3).pptx](https://github.com/aws-samples/aws-microservices-deploy-options/files/1891501/slides-for-arun.3.pptx)

**Comment by sanjay1869** [comment]
Nice slide, explained well
