### ISSUE TITLE
CanaryDeploymentType parameter not used in greeting-sam.yaml SAM template

### ISSUE THREAD

**Issue by danilop** [aws-samples/aws-microservices-deploy-options#223]
In the `greeting-sam.yaml` SAM template, the `CanaryDeploymentType` parameter is not used. In fact, the `DeploymentPreference` for the `GreetingFunction` is hardcoded to `Canary10Percent5Minutes` instead of referencing the `CanaryDeploymentType` parameter.

**Comment by arun-gupta** [comment]
@allinwonder can you take a look at this?
