### ISSUE TITLE
Webapp endpoint gives {"message":"Missing Authentication Token"}

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-microservices-deploy-options#251]
Webapp endpoint created using Fargate Lambda pipeline gives the following error:

```
{"message":"Missing Authentication Token"}
```

This is after https://github.com/aws-samples/aws-microservices-deploy-options/pull/247.

Latest instructions are at https://github.com/aws-samples/aws-microservices-deploy-options#deployment-pipeline-aws-codepipeline-1.

**Comment by arun-gupta** [comment]
Completed with https://github.com/aws-samples/aws-microservices-deploy-options/pull/247

**Comment by arun-gupta** [comment]
Instructions need to be updated

**Comment by YaRuliY** [comment]
http://www.awslessons.com/2017/aws-api-gateway-missing-authentication-token/
