### ISSUE TITLE
Intuitive name for the repo

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-microservices-deploy-options#32]
Need a more intuitive name for the repo

@christopherhein suggested `aws-application-deploy-option` and `apps-on-aws`

Another option `microservices-on-aws`

More suggestions?

**Comment by ghoshtapo** [comment]
I like microservices_on_aws or microsvcs-deploy-on-aws

**Comment by christopherhein** [comment]
I dig `aws-microservices-deploy-options` that gives it a little more grounding

**Comment by arun-gupta** [comment]
Filed an internal ticket

**Comment by arun-gupta** [comment]
Repo is renamed to https://github.com/aws-samples/aws-microservices-deploy-options
