### ISSUE TITLE
Slide Feedback

### ISSUE THREAD

**Issue by christopherhein** [aws-samples/aws-microservices-deploy-options#89]
Stub for slide feedback.

**Comment by christopherhein** [comment]
Slide deck looks great so far! 

* slide 6 (dev)
  * + dev prod parity (3 in the list partially covers this but could be explicit)
  * + debugging (goes along with bottlenecks/logging/monitoring)
  * Continous Intergration 
  * Continous Delivery
* slide 6 (ops)
  * Cost
* slide 19-20
  * Less ECS / Fargate specific
* slide 22 
  * add EKS logo, maybe put a "preview" sash over it.
* slide 51
  * make more generic this might need partner solutions as well, but calling out CloudWatch, Elastic, Kibana, x-ray, etc
* slide 58
  * did the number drop, in my most recent deck i have 63%
* slide 65-68
  * do we need the tenets?
* slide 75
  * add the helm logo
* slide 76
  * Tiller gets info via the client, when you use `stable/spinnaker` as the chart it will get the latest bits from one of the repos in your local helm config and sends the interpolated configs to tiller which handles the rest
  * repo doesn't need to be configured with tiller, local does
  * In tiller it stores it in the configs it deploys labels, annotations etc. It might store some manually in etcd need to verify though.
  * passes via gRPC like you have in the deck. this looks great except I think we need to remove the Helm repo -> tiller server arrow
* slide 81
  * add ksonnet logo
* slide 82
  * @christopherhein remake the diagram
* Slide 83
  * revisit the code block as it wraps poorly

**Comment by arun-gupta** [comment]
Thanks for the lovely feedback.

Send another PR when an updated version of the diagram is available.

CNCF numbers are accurate per the third chart shown at https://www.cncf.io/blog/2017/12/06/cloud-native-technologies-scaling-production-applications/
